unit Unit1;

interface

uses
  Windows, Messages, SysUtils, Variants, Classes, Graphics, Controls, Forms,
  Dialogs, StdCtrls;
type
  ReturnResult=record
    Status:Integer;
    Time:Double;
    Information:Cardinal;
    Memory:Integer;
  end;
type
  TForm1 = class(TForm)
    btn1: TButton;
    btn2: TButton;
    procedure btn1Click(Sender: TObject);
    procedure btn2Click(Sender: TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  Form1: TForm1;

implementation

{$R *.dfm}
function DoIt(Cmd:AnsiString;TimeLimit:Cardinal;MemoryLimit:Integer):Pointer;stdcall;
external 'ProjectTimerOne.dll';

FUNCTION EXCEPTIONCODE(EC:CARDINAL):ANSISTRING;
BEGIN
  CASE EC OF
   STATUS_ACCESS_VIOLATION:RESULT:='EXCEPTION_ACCESS_VIOLATION';
   STATUS_IN_PAGE_ERROR:RESULT:='EXCEPTION_IN_PAGE_ERROR';
   STATUS_INVALID_HANDLE:RESULT:='EXCEPTION_INVALID_HANDLE';
   STATUS_NO_MEMORY:RESULT:='EXCEPTION_NO_MEMORY';
   STATUS_ILLEGAL_INSTRUCTION:RESULT:='EXCEPTION_ILLEGAL_INSTRUCTION';
   STATUS_NONCONTINUABLE_EXCEPTION:RESULT:='EXCEPTION_NONCONTINUABLE_EXCEPTION';
   STATUS_INVALID_DISPOSITION:RESULT:='EXCEPTION_INVALID_DISPOSITION';
   STATUS_ARRAY_BOUNDS_EXCEEDED:RESULT:='EXCEPTION_ARRAY_BOUNDS_EXCEEDED';
   STATUS_FLOAT_DENORMAL_OPERAND:RESULT:='EXCEPTION_FLOAT_DENORMAL_OPERAND';
   STATUS_FLOAT_DIVIDE_BY_ZERO:RESULT:='EXCEPTION_FLOAT_DIVIDE_BY_ZERO';
   STATUS_FLOAT_INEXACT_RESULT:RESULT:='EXCEPTION_FLOAT_INEXACT_RESULT';
   STATUS_FLOAT_INVALID_OPERATION:RESULT:='EXCEPTION_INVALID_OPERATION_OR_DIVIDE_BY_ZERO';
   STATUS_FLOAT_OVERFLOW:RESULT:='EXCEPTION_FLOAT_OVERFLOW';
   STATUS_FLOAT_STACK_CHECK:RESULT:='EXCEPTION_FLOAT_STACK_CHECK';
   STATUS_FLOAT_UNDERFLOW:RESULT:='EXCEPTION_FLOAT_UNDERFLOW';
   STATUS_INTEGER_DIVIDE_BY_ZERO:RESULT:='EXCEPTION_INTEGER_DIVIDE_BY_ZERO';
   STATUS_INTEGER_OVERFLOW:RESULT:='EXCEPTION_INTEGER_OVERFLOW';
   STATUS_PRIVILEGED_INSTRUCTION:RESULT:='EXCEPTION_PRIVILEGED_INSTRUCTION';
   STATUS_STACK_OVERFLOW:RESULT:='EXCEPTION_STACK_OVERFLOW';
   STATUS_CONTROL_C_EXIT:RESULT:='EXCEPTION_CONTROL_C_EXIT';
   MAXIMUM_WAIT_OBJECTS:RESULT:='EXCEPTION_WAIT_OBJECTS';
   ELSE BEGIN
     RESULT:=IntToStr(EC);
   END;
  END;
END;


procedure TForm1.btn1Click(Sender: TObject);
var
 p:Pointer;
 r:ReturnResult;
begin
p:=DoIt('C:\SLEEP1500.exe',2000,1024);
CopyMemory(@r,p,SizeOf(r));
ShowMessage(IntToStr(r.Status));
ShowMessage(FloatToStr(r.Time));
ShowMessage(EXCEPTIONCODE(r.Information));
ShowMessage(FloatToStr(r.Memory));
end;

procedure TForm1.btn2Click(Sender: TObject);
begin
ShowMessage(IntToStr(EXCEPTION_ACCESS_VIOLATION));

end;

end.
